[package]
name = "rdom"
version = "0.1.0"
edition = "2021"

[lib]
path = "mod.rs"

[dependencies]
html5ever = "0.27"
markup5ever_rcdom = "0.3"
rutils = { git = "ssh://git@github.com/Vehmloewff/rutils.git", rev = "0.3.0" }
